/*
  Shared pass-breakdown instrumentation (GSIM_EMIT_PHASE_TIMING=1): wall time per
  region, printed to stderr. Pure measurement - never changes generated bytes.
  Same contract as the file-local EmitPhaseTimer in cppEmitter.cpp, reusable from
  any translation unit (graphPartition / mergeNodes / seedOrder2).
*/
#ifndef PHASE_TIMER_H
#define PHASE_TIMER_H

#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <string>

namespace phasetimer {

inline bool enabled() {
  const char* env = std::getenv("GSIM_EMIT_PHASE_TIMING");
  return env != nullptr && env[0] != '\0' && env[0] != '0';
}

inline std::chrono::steady_clock::time_point now() { return std::chrono::steady_clock::now(); }

// Print elapsed ms since t0 under a caller-chosen label. Call sites that need a
// dynamic label build it only when timing is enabled.
inline void mark(const char* name, std::chrono::steady_clock::time_point t0) {
  if (!enabled() || name == nullptr || name[0] == '\0') return;
  long ms = std::chrono::duration_cast<std::chrono::milliseconds>(now() - t0).count();
  fprintf(stderr, "[gpart-phase] %s = %ld ms\n", name, ms);
}

}  // namespace phasetimer

struct PhaseTimer {
  const char* phaseName;
  std::chrono::steady_clock::time_point begin;
  explicit PhaseTimer(const char* n)
      : phaseName(n), begin(phasetimer::now()) {}
  ~PhaseTimer() { phasetimer::mark(phaseName, begin); }
};

// Scoped label helper: defer building a dynamic label string until timing is
// known to be enabled (name construction stays free otherwise).
struct PhaseName {
  std::string storage;
  explicit PhaseName(const char* prefix, const char* tag) {
    if (!phasetimer::enabled()) return;
    storage = prefix;
    if (tag && tag[0]) { storage += '.'; storage += tag; }
  }
  const char* c_str() const { return storage.c_str(); }  // empty when disabled; mark() skips it
};

#endif  // PHASE_TIMER_H
